pipeline:
  name: build_and_test_pipeline
  identifier: build_and_test_pipeline
  projectIdentifier: javatodoapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubmendelev
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Unit test
                  identifier: Unit_test
                  spec:
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: cd backend && mvn -B test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/target/surefire-reports/*.xml"
              - step:
                  type: Background
                  name: postgres
                  identifier: postgres
                  spec:
                    image: postgres:15-alpine
                    shell: Sh
                    envVariables:
                      POSTGRES_DB: todoapp_int
                      POSTGRES_USER: todo
                      POSTGRES_PASSWORD: todo
                    portBindings:
                      "5432": "5432"
              - step:
                  type: Run
                  name: Integration tests
                  identifier: Integration_tests
                  spec:
                    image: maven:3.9-eclipse-temurin-21
                    shell: Bash
                    envVariables:
                      TEST_DB_HOST: postgres
                      TEST_DB_PORT: "5432"
                      TEST_DB_NAME: todoapp_int
                      TEST_DB_USER: todo
                      TEST_DB_PASSWORD: todo
                    command: |-
                      # Wait for Postgres to be ready
                      echo "Waiting for Postgres..."
                      for i in {1..30}; do
                        if nc -z postgres 5432 2>/dev/null; then
                          echo "Postgres is ready!"
                          break
                        fi
                        echo "Attempt $i: Postgres not ready yet..."
                        sleep 2
                      done

                      # Run integration tests
                      cd backend
                      mvn -B -P integration-tests test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/target/failsafe-reports/*.xml"
                          - "**/target/surefire-reports/*.xml"
              - step:
                  type: Run
                  name: Compute_Semver
                  identifier: Compute_Semver
                  spec:
                    shell: Bash
                    command: |-
                      set -e

                      # 1) Get the last git tag (fallback to 0.0.0)
                      LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
                      echo "Last tag: $LAST_TAG"

                      # 2) Split into major.minor.patch
                      MAJOR=$(echo "$LAST_TAG" | cut -d. -f1)
                      MINOR=$(echo "$LAST_TAG" | cut -d. -f2)
                      PATCH=$(echo "$LAST_TAG" | cut -d. -f3)

                      # 3) Bump what you want (here: PATCH)
                      PATCH=$((PATCH+1))

                      NEW_TAG="${MAJOR}.${MINOR}.${PATCH}"
                      echo "New tag: $NEW_TAG"

                      # 4) Export to Harness so next steps can read it
                      export IMAGE_TAG="$NEW_TAG"
                    outputVariables:
                      - name: IMAGE_TAG
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPush_Backend
                  identifier: BuildAndPush_Backend
                  spec:
                    connectorRef: mendelev_dockerhub
                    repo: yuridevpro/todo-app-java-backend
                    tags:
                      - <+execution.steps.Compute_Semver.output.outputVariables.IMAGE_TAG>
                    context: backend
                    dockerfile: backend/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPush_Frontend
                  identifier: BuildAndPush_Frontend
                  spec:
                    connectorRef: mendelev_dockerhub
                    repo: yuridevpro/todo-app-java-frontend
                    tags:
                      - <+execution.steps.Compute_Semver.output.outputVariables.IMAGE_TAG>
                    context: frontend
                    dockerfile: frontend/Dockerfile
              - step:
                  type: AquaTrivy
                  name: SAST_Backend1
                  identifier: SAST_Backend1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: <+execution.steps.Compute_Semver.output.outputVariables.IMAGE_TAG>
                      name: yuridevpro/todo-app-java-backend
              - step:
                  type: AquaTrivy
                  name: SAST_Frontend
                  identifier: SAST_Frontend
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: <+execution.steps.Compute_Semver.output.outputVariables.IMAGE_TAG>
                      name: yuridevpro/todo-app-java-frontend
              - step:
                  type: Run
                  name: Push Git Tag
                  identifier: Push_Git_Tag
                  spec:
                    shell: Bash
                    envVariables:
                      GITHUB_TOKEN: <+secrets.getValue("login-github")>
                    command: |-
                      set -e
                      NEW_TAG="<+execution.steps.Compute_Semver.output.outputVariables.IMAGE_TAG>"
                      REPO="Mendelev/java-demo-app"
                      COMMIT_SHA="<+codebase.commitSha>"
                      
                      echo "Creating tag: $NEW_TAG for commit: $COMMIT_SHA"
                      
                      # Create the tag object
                      TAG_RESPONSE=$(curl -s -X POST \
                        -H "Authorization: token $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/$REPO/git/tags" \
                        -d "{\"tag\":\"$NEW_TAG\",\"message\":\"Release $NEW_TAG\",\"object\":\"$COMMIT_SHA\",\"type\":\"commit\",\"tagger\":{\"name\":\"Harness CI\",\"email\":\"ci@harness.io\"}}")
                      
                      TAG_SHA=$(echo "$TAG_RESPONSE" | grep -o '"sha": "[^"]*"' | head -1 | cut -d'"' -f4)
                      
                      if [ -z "$TAG_SHA" ]; then
                        echo "Failed to create tag object. Response: $TAG_RESPONSE"
                        exit 1
                      fi
                      
                      # Create the reference
                      REF_RESPONSE=$(curl -s -X POST \
                        -H "Authorization: token $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/$REPO/git/refs" \
                        -d "{\"ref\":\"refs/tags/$NEW_TAG\",\"sha\":\"$TAG_SHA\"}")
                      
                      echo "Successfully created tag $NEW_TAG"
                      echo "Response: $REF_RESPONSE"
    - stage:
        name: Deploy to K8s
        identifier: Deploy_to_K8s
        description: Deploy to Kubernetes after successful build
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: javatodoappservice
          environment:
            environmentRef: myk8slocal
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infraestrutucrek8slocal
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
